### ISSUE TITLE
Some users don't have an image_original field

### ISSUE THREAD

**Issue by shawnrc** [shawnrc/kemohno#19]
Getting a lot of this
```
ERROR  01:27:14.824 [qtp933547598-18]  spark.http.matching.GeneralError -
--
  | java.util.NoSuchElementException: missing field image_original
  | at me.shawnrc.kemohno.SharedKt.getString(Shared.kt:15)
  | at me.shawnrc.kemohno.KemohnoKt$main$$inlined$apply$lambda$3.invoke(Kemohno.kt:143)
  | at me.shawnrc.kemohno.KemohnoKt$main$$inlined$apply$lambda$3.invoke(Kemohno.kt)
  | at spark.kotlin.Http$post$1.handle(Http.kt:579)
  | at spark.RouteImpl$1.handle(RouteImpl.java:72)
  | at spark.http.matching.Routes.execute(Routes.java:61)
  | at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
  | at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
  | at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
  | at org.eclipse.jetty.server.Server.handle(Server.java:564)
  | at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
  | at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
  | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
  | at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
  | at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
  | at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
  | at java.lang.Thread.run(Thread.java:748)
```

Not entirely sure what specifically causes a user not to have this field, but it looks like `image_512` is present even on accounts without a profile picture set - probably just need to default to that lad instead.

**Comment by shawnrc** [comment]
Resolved by a269758
