### ISSUE TITLE
occasional "A JSONObject text must begin with '{' at 1" error

### ISSUE THREAD

**Issue by shawnrc** [shawnrc/kemohno#4]
The problem lives [here](https://github.com/shawnrc/kemohno/blob/774d011e0d9762f30b40136dec6d53a49c02bde6/src/main/kotlin/me/shawnrc/kemohno/SlackClient.kt#L51)

Need to figure out a way to concisely go down the error path on each condition.

Full error:
```

[qtp2049738751-17] ERROR spark.http.matching.GeneralError -
--
  | org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
  | at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
  | at org.json.JSONObject.<init>(JSONObject.java:198)
  | at org.json.JSONObject.<init>(JSONObject.java:325)
  | at khttp.responses.GenericResponse.getJsonObject(GenericResponse.kt:225)
  | at me.shawnrc.kemohno.SlackClient.request(SlackClient.kt:51)
  | at me.shawnrc.kemohno.SlackClient.sendMessage(SlackClient.kt:31)
  | at me.shawnrc.kemohno.KemohnoKt$main$$inlined$apply$lambda$1.invoke(Kemohno.kt:43)
  | at me.shawnrc.kemohno.KemohnoKt$main$$inlined$apply$lambda$1.invoke(Kemohno.kt)
  | at spark.kotlin.Http$post$1.handle(Http.kt:579)
  | at spark.RouteImpl$1.handle(RouteImpl.java:72)
  | at spark.http.matching.Routes.execute(Routes.java:61)
  | at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
  | at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
  | at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
  | at org.eclipse.jetty.server.Server.handle(Server.java:564)
  | at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
  | at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
  | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
  | at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
  | at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
  | at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
  | at java.lang.Thread.run(Thread.java:748)
```

**Comment by shawnrc** [comment]
resolved by #9
